import Config

for {key, value} <- [
      {"SECRET_KEY_BASE", "dev-secret-key-base"},
      {"RELEASE_COOKIE", "dev-release-cookie"},
      {"PUBLIC_HOST", "localhost"},
      {"PLEX_TOKEN", "dev-plex-token"}
    ] do
  if is_nil(System.get_env(key)) do
    System.put_env(key, value)
  end
end

config :nerve_center, :paths,
  db: Path.expand("../tmp/dev/nerve_center.sqlite3", __DIR__),
  backups: Path.expand("../tmp/dev/backups", __DIR__),
  log_dir: Path.expand("../tmp/dev/logs", __DIR__),
  app_log: Path.expand("../tmp/dev/logs/app.log", __DIR__)

# Configure your database
config :nerve_center, NerveCenter.Repo,
  database: Path.expand("../tmp/dev/nerve_center.sqlite3", __DIR__),
  pool_size: 5,
  journal_mode: :wal,
  synchronous: :normal,
  busy_timeout: 5_000,
  foreign_keys: :on,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nerve_center, NerveCenterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4041],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "odso4LDOqCJhNLCswhms/+FPgJxLyb3odj4ZdA1KFUse1GTUouEfYLNC1sYiicPJ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:nerve_center, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:nerve_center, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :nerve_center, NerveCenterWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/nerve_center_web/router\.ex$"E,
      ~r"lib/nerve_center_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

config :nerve_center, dev_routes: false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
